let g:ruby_host_prog = '~/.gem/ruby/2.3.0/bin/neovim-ruby-host'
"let g:python_host_prog = '~/.pyenv/versions/2.7.13/envs/neovim2/bin/python'
"let g:python3_host_prog = '~/.pyenv/versions/3.6.0/envs/neovim3/bin/python'

" neovim sensible
" Use "hybrid" (both absolute and relative) line numbers
set number
set relativenumber

" use the system clipboard
set clipboard=unnamed

set colorcolumn=78

" Set new mapleader default key.
let mapleader=","

" searching
set ignorecase
set smartcase
set showmatch
set hlsearch

set shiftwidth=4
set softtabstop=4
set expandtab

set visualbell
"set cursorline
set ttyfast

" vim feels more natural when split windows below and right
set splitbelow
set splitright

" don't use swapfile
set noswapfile
set nowritebackup

" we show the mode with lightline
set noshowmode
set laststatus=2

set lazyredraw

" jump between split windows with ctrl-h,j,k,l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" remove search highlight
nnoremap <leader><space> :nohlsearch<CR>
" center the screen
nnoremap <space> zz

if has('nvim')
"  set termguicolors
endif

" do not show stupid q: window
nnoremap q: :q

" allow saving of files as sudo when I forgot to start vim using sudo
cnoremap w!! w !sudo tee > /dev/null %

" fast saving
nmap <leader>w :w!<CR>

" terminal (for nvim only)
if has('nvim')
  " exit from terminal mode using ESC key
  "tnoremap <Esc> <C-\><C-n>
endif

if !empty(&viminfo)
  set viminfo^=!
endif

" plugins
function! s:StripTrailingWhitespace(...)
  if !&binary && &filetype != 'diff'
    let l:saved_winview = winsaveview()
    keeppatterns %s/\v\s+$//e
    call winrestview(l:saved_winview)
  endif
endfunction

if has('autocmd')
  " done by vim-plug
  "filetype plugin indent on
  augroup vimrc
    au!
    " Re-source .vimrc on save so changes are effective immediately:
    au BufWritePost vimrc nested source %

    " save when losing the focus
    au FocusLost * :wa
  augroup END

  augroup syntax
    au!

    " syntax highlighting for .md files
    au BufRead,BufNewFile *.md set filetype=markdown
    " syntax highlighting for .conf files
    au BufRead,BufNewFile *.conf set filetype=conf
  augroup END

  augroup plugins
    au!

    " =========== vim-terraform ===========
    let g:terraform_align = 1
    let g:terraform_remap_spacebar = 1
    let g:terraform_fmt_on_save = 1

    " =========== plugin clean whitespaces ===========
    au BufWritePre * call s:StripTrailingWhitespace()
  augroup END
endif

" =========== NerdTree ===========
nmap <C-n> :NERDTreeToggle<CR>
noremap <Leader>n :NERDTreeToggle<CR>
noremap <Leader>f :NERDTreeFind<CR>

let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['.DS_Store', '\.git$', '\.hg$']

"let base16colorspace=256
"colorscheme base16-tomorrow-night
colorscheme nord

" vim:ts=2:sw=2:et
