" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
"Plug 'airblade/vim-gitgutter'
Plug 'mhinz/vim-signify'
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
"Plug 'docker/docker', { 'rtp': '/contrib/syntax/vim' }
Plug 'ntpeters/vim-better-whitespace'
"Plug 'puppetlabs/puppet-syntax-vim'
"Plug 'saltstack/salt-vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'hashivim/vim-terraform'

" =========== color ===========
"Plug 'chriskempson/base16-vim'
"Plug 'arcticicestudio/nord-vim'
Plug 'dabio/nord-vim', { 'branch': 'vim-signify' }

" Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
" Plug 'zchee/deoplete-go', { 'do': 'make' }

" Initialize plugin system
call plug#end()

"let g:python_host_prog = '/Users/dan/.pyenv/versions/2.7.13/envs/neovim2/bin/python'
"let g:python3_host_prog = '/Users/dan/.pyenv/versions/3.6.0/envs/neovim3/bin/python'

" neovim sensible
" Use "hybrid" (both absolute and relative) line numbers
set number
set relativenumber

" use the system clipboard
set clipboard=unnamed

set colorcolumn=78

" Set new mapleader default key.
let mapleader=","

" searching
set ignorecase
set smartcase
set showmatch
set hlsearch

set shiftwidth=4
set softtabstop=4

set visualbell
"set cursorline
set ttyfast

" vim feels more natural when split windows below and right
set splitbelow
set splitright

" don't use swapfile
set noswapfile
set nowritebackup

" we show the mode with lightline
set noshowmode
set laststatus=2

set lazyredraw

" deactivate arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" jump between split windows with ctrl-h,j,k,l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" remove search highlight
nnoremap <leader><space> :nohlsearch<CR>
" center the screen
nnoremap <space> zz

if has('nvim')
  set termguicolors
endif

" do not show stupid q: window
nmap q: :q

" allow saving of files as sudo when I forgot to start vim using sudo
cmap w!! w !sudo tee > /dev/null %

" fast saving
nmap <leader>w :w!<CR>

if !empty(&viminfo)
  set viminfo^=!
endif

if has('autocmd')
  " done by vim-plug
  "filetype plugin indent on
  augroup vimrc
    au!
    " Re-source .vimrc on save so changes are effective immediately:
    au BufWritePost vimrc nested source %

    " save when losing the focus
    au FocusLost * :wa
  augroup END

  augroup syntax
    au!

    " syntax highlighting for .md files
    au BufRead,BufNewFile *.md set filetype=markdown
  augroup END

  augroup plugins
    au!

    " =========== vim-go ===========
    let g:go_fmt_command = "goimports"
    let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
    let g:go_metalinter_autosave = 1
    let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
    " let g:go_auto_sameids = 1

    " =========== vim-terraform ===========
    let g:terraform_align = 1
    let g:terraform_fmt_on_save = 1

    " =========== vim-better-whitespace ===========
    au BufWritePre * StripWhitespace

    " =========== ctrlp ===========
    let g:ctrlp_user_command = ['.git', 'cd %s ; git ls-files -co --exclude-standard']

    " =========== terraform ===========
    let g:terraform_align = 1
    let g:terraform_remap_spacebar = 1
    let g:terraform_fmt_on_save = 1

    " =========== nord ===========
    let g:nord_italic_comments = 1
    let g:nord_uniform_status_lines = 1

    " =========== lightline ===========
    "let g:lightline = {'colorscheme': 'wombat'}
    let g:lightline = {'colorscheme': 'nord'}

    " =========== vim-signify ===========
    let g:signify_vcs_list = [ 'git', 'hg' ]
    let g:signify_sign_show_count = 0
    let g:signify_sign_change = '~'

  augroup END

endif

" =========== NerdTree ===========
nmap <C-n> :NERDTreeToggle<CR>
noremap <Leader>n :NERDTreeToggle<CR>
noremap <Leader>f :NERDTreeFind<CR>

let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['.DS_Store', '\.git$', '\.hg$']

" =========== deoplete ===========
" if has('nvim')
"   let g:deoplete#enable_at_startup = 1
"
"   let g:deoplete#sources#go#sort_class = ['func', 'type', 'var', 'const']
"   let g:deoplete#sources#go#align_class = 1
"
"   " deoplete tab-complete
"   inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
"   inoremap <expr><s-tab> pumvisible() ? "\<c-p>" : "\<tab>"
" endif

"let base16colorspace=256
"colorscheme base16-tomorrow-night
"colorscheme base16-chalk
"colorscheme base16-default-dark
"colorscheme base16-classic-dark
"colorscheme base16-irblack
colorscheme nord

"highlight DiffAdd cterm=bold ctermbg=none ctermfg=2
"highlight DiffDelete cterm=bold ctermbg=none ctermfg=1
"highlight DiffChange cterm=bold ctermbg=none ctermfg=3

" vim:ts=2:sw=2:et
