update
doctor
install bash-completion
install go
install rbenv rbenv-default-gems rbenv-gem-rehash ruby-build
install tig
install macvim
install heroku-toolbelt
install xctool
install fish
install unrar
tap phinze/cask
install brew-cask
cask install google-chrome
cask install google-drive
cask install textmate
cask install appzapper
cask install menumeters
cask install mplayerx
cask install atom
cask install boxcryptor-classic
cask install spotify
cask install flux
